apiVersion: v1
kind: Pod
metadata:
  name: nginx-ceph
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /data
          name: s3-vol
  volumes:
    - name: s3-vol
      persistentVolumeClaim:
        claimName: dataset-ceph
