apiVersion: v1
kind: ConfigMap
metadata:
  name: autonomy-cephfs
data:
  # 类属性键；每一个键都映射到一个简单的值
  mds.namespace: cephfs
  mount.point: /<mount-dir>
  auth.id: client_id
  # 类文件键，|表示有多行数据
  conf.file: |
    ....# 省略
  auth.keyring: |
    [client.id_name]
        key = xxxxxxx==   #自己的keyring  
        caps mds = "allow rw"
        caps mon = "allow r"
        caps osd = "allow rwx pool=cephfs_data"
