apiVersion: v1
kind: Pod
metadata:
  name: nginx-cephfs
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /data
          name: autonomy-gpu-volume
  volumes:
    - name: autonomy-gpu-volume
      persistentVolumeClaim:
        claimName: dataset-cephfs
